### ISSUE TITLE
Question: Fetch

### ISSUE THREAD

**Issue by Ordiel** [quinton-ashley/java2js#2]
I was wondering if it would be at all possible to produce a [`fetch`](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) call from java code? If so, what would be the java code to produce such a javascript code for that call?

**Comment by quinton-ashley** [comment]
You can use the Scanner class. It only does text files for now though.

What were you hoping to fetch?

https://github.com/quinton-ashley/java2js/blob/main/jdk/java/util/Scanner.js

**Comment by Ordiel** [comment]
Following up on the [first issue I opened](https://github.com/quinton-ashley/java2js/issues/1) I was expecting to be able to do something like:

```java
public class Person {
	private int id;
	private String name;
	private String lastName;
	private int age;

	public void fetchPerson(int id, Function</* ?? */> handleResponse) {
		// Some magic here to produce the fetch call; this is what I don't know if its possible
	}

}
```
and produce something like:

```javascript
class Person {
  constructor() {
    this.id = 0;
    this.name = null;
    this.lastName = null;
    this.age = 0;
  }
  
  function fetchPerson(id, handleResponse) {
    fetch(`http://myhost.com/person?id=${id}`).then(response => handleResponse(response))
  }
  
}
```

**Comment by quinton-ashley** [comment]
Try using a Scanner with a File object and you can get the text of the file as if it was loaded in Java from the local file system.

```js
new Scanner(new File("http://myhost.com/person?id=" + id));
```
